apiVersion: v1
kind: BuildConfig
metadata:
  name: {{project_prefix}}-pipeline
  namespace: 
  labels:
    name: {{project_prefix}}-pipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "{{template_dc}}", "namespace": "{{project_prefix}}-dev", "kind": "DeploymentConfig"},{"name": "{{template_dc}}", "namespace": "{{project_prefix}}-test", "kind": "DeploymentConfig"}]'
spec:
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node {
          stage 'buildInDevelopment'
          openshiftBuild(namespace: '{{project_prefix}}-dev', buildConfig: '{{template_bc}}', showBuildLogs: 'true')
        }

        node {
          stage 'deployInDevelopment'
          openshiftDeploy(namespace: '{{project_prefix}}-dev', deploymentConfig: '{{template_dc}}')
          openshiftScale(namespace: '{{project_prefix}}-dev', deploymentConfig: '{{template_dc}}',replicaCount: '2')
        }

        node {
          stage 'approveTestDeployment' 
          input 'Promote the Dev image to Test?'
        }

        node {
          stage 'deployInTesting'
          openshiftTag(namespace: '{{project_prefix}}-dev', sourceStream: '{{template_bc}}',  sourceTag: 'latest', destinationNamespace: '{{project_prefix}}-test',  destinationStream: '{{template_bc}}', destinationTag: 'latest')
          openshiftDeploy(namespace: '{{project_prefix}}-test', deploymentConfig: '{{template_dc}}')
          openshiftScale(namespace: '{{project_prefix}}-test', deploymentConfig: '{{template_dc}}',replicaCount: '3')
        }
  output:
  resources:
  postCommit: